// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewGame struct {
	Name    string `json:"name"`
	Price   string `json:"price"`
	StoreID string `json:"store_id"`
}

type NewStore struct {
	Name string `json:"name"`
}
